version: "3"  
services:

  backend:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql
    ports:
      - "8080:8080"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: food
      MYSQL_PASSWORD: application
      MYSQL_DATABASE: foodapplication
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
