apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysqldb-service
spec:
  selector:
    app: mysqldb-deployment
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP