apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-fastfood-ingress
spec:
  rules:
    - http:
        paths:
        - path: /cliente/registre/
          pathType: Prefix
          backend:
            service:
              name: app-fastfood  # Nome do Service a ser roteado
              port:
                number: 80  # Porta do Service a ser roteado
